In [1]:
import pandas as pd
import os

In [2]:
old_data = pd.read_csv(os.getcwd().replace('code','') + f'/data/cleaned_prof_data_v4.csv')

In [9]:
old_data

,name,affiliation,homepage,scholar_id,citations,h-index
0,P. Vassalos,AUEB,http://pubs.dbs.uni-leipzig.de/aa/aff/Greece/A...,NOSCHOLARPAGE,NaN,NaN
1,Stavros Toumpis,AUEB,https://195.251.255.130/en/faculty/toumpis-sta...,LyiVPKEAAAAJ,2804.0,21.0
2,Ion Androutsopoulos,AUEB,http://www.aueb.gr/users/ion,4UJm5EQAAAAJ,11918.0,42.0
3,Michalis K. Titsias,AUEB,http://www.aueb.gr/users/mtitsias,B-SbkAwAAAAJ,5255.0,30.0
4,Vasilios A. Siris,AUEB,http://www.aueb.gr/users/vsiris,Vj3O0cEAAAAJ,5967.0,31.0
...,...,...,...,...,...,...
20644,Ali C. Begen,Özyeğin University,https://ali.begen.net,ZIZWsXoAAAAJ,5964.0,34.0
20645,Erhan Öztop,Özyeğin University,https://robotics.ozyegin.edu.tr/members/erhan-...,A8YEQMMAAAAJ,3702.0,28.0
20646,Yasar Safkan,Özyeğin University,https://cs.ozyegin.edu.tr/en/faculty/yasarsafkan,NOSCHOLARPAGE,NaN,NaN
20647,Hasan Sözer,Özyeğin University,https://faculty.ozyegin.edu.tr/hsozer,L3FuUX0AAAAJ,847.0,16.0
20648,Emre Sefer,Özyeğin University,http://www.emresefer.com,W5qWthcAAAAJ,253.0,10.0

In [4]:
old_data.loc[old_data['name']=="En-Hong Chen"]

,name,affiliation,homepage,scholar_id,citations,h-index
12002,En-Hong Chen,USTC,http://staff.ustc.edu.cn/~cheneh,NOSCHOLARPAGE,NaN,NaN

In [5]:
scraped_data = pd.read_csv(os.getcwd().replace('code','') + f'/data/replaced_bad_prof_data_12000_20650.csv')

In [12]:
scraped_data

,Name,affiliation,homepage,scholar-id,citations,h-index
0,En-Hong Chen,USTC,http://staff.ustc.edu.cn/~cheneh,Q9h02J0AAAAJ,17678.0,64.0
1,Lihua Yue,USTC,http://www.jucs.org/jucs_articles_by_author/Yu...,NaN,NaN,NaN
2,Joseph E. Gonzalez,Univ. of California - Berkeley,http://www.cs.berkeley.edu/~jegonzal,gM2WW9UAAAAJ,18885.0,52.0
3,Ronald S. Fearing,Univ. of California - Berkeley,https://robotics.eecs.berkeley.edu/~ronf,uA0kNBUAAAAJ,25254.0,75.0
4,Armando Fox,Univ. of California - Berkeley,https://www.eecs.berkeley.edu/Faculty/Homepage...,GXJqtYUAAAAJ,44883.0,74.0
...,...,...,...,...,...,...
2118,Ke Chen,Zhejiang University,http://mypage.zju.edu.cn/kechenpage,0Zv2m-cAAAAJ,838.0,15.0
2119,Hongzhi Wu,Zhejiang University,http://www.cad.zju.edu.cn/home/hwu,NaN,NaN,NaN
2120,Lu Chen,Zhejiang University,https://person.zju.edu.cn/luchen,NaN,NaN,NaN
2121,Yang Yang,Zhejiang University,http://yangy.org,NaN,NaN,NaN
2122,Jian-Ling Sun,Zhejiang University,https://person.zju.edu.cn/en/sunjl,NaN,NaN,NaN

In [11]:
scraped_data = scraped_data.drop(['Unnamed: 0'], axis=1)

In [24]:
new_data = old_data.copy()

In [25]:
new_data

,name,affiliation,homepage,scholar_id,citations,h-index
0,P. Vassalos,AUEB,http://pubs.dbs.uni-leipzig.de/aa/aff/Greece/A...,NOSCHOLARPAGE,NaN,NaN
1,Stavros Toumpis,AUEB,https://195.251.255.130/en/faculty/toumpis-sta...,LyiVPKEAAAAJ,2804.0,21.0
2,Ion Androutsopoulos,AUEB,http://www.aueb.gr/users/ion,4UJm5EQAAAAJ,11918.0,42.0
3,Michalis K. Titsias,AUEB,http://www.aueb.gr/users/mtitsias,B-SbkAwAAAAJ,5255.0,30.0
4,Vasilios A. Siris,AUEB,http://www.aueb.gr/users/vsiris,Vj3O0cEAAAAJ,5967.0,31.0
...,...,...,...,...,...,...
20644,Ali C. Begen,Özyeğin University,https://ali.begen.net,ZIZWsXoAAAAJ,5964.0,34.0
20645,Erhan Öztop,Özyeğin University,https://robotics.ozyegin.edu.tr/members/erhan-...,A8YEQMMAAAAJ,3702.0,28.0
20646,Yasar Safkan,Özyeğin University,https://cs.ozyegin.edu.tr/en/faculty/yasarsafkan,NOSCHOLARPAGE,NaN,NaN
20647,Hasan Sözer,Özyeğin University,https://faculty.ozyegin.edu.tr/hsozer,L3FuUX0AAAAJ,847.0,16.0
20648,Emre Sefer,Özyeğin University,http://www.emresefer.com,W5qWthcAAAAJ,253.0,10.0

In [37]:
for i in range(scraped_data.shape[0]):
    row = scraped_data.loc[i]
    row_to_replace = new_data.loc[(new_data['name']==row['Name']) & (new_data['affiliation'] == row['affiliation'])]
    index = row_to_replace.index.tolist()[0]
    new_data.loc[index] = row.tolist()

In [38]:
new_data

,name,affiliation,homepage,scholar_id,citations,h-index
0,P. Vassalos,AUEB,http://pubs.dbs.uni-leipzig.de/aa/aff/Greece/A...,NOSCHOLARPAGE,NaN,NaN
1,Stavros Toumpis,AUEB,https://195.251.255.130/en/faculty/toumpis-sta...,LyiVPKEAAAAJ,2804.0,21.0
2,Ion Androutsopoulos,AUEB,http://www.aueb.gr/users/ion,4UJm5EQAAAAJ,11918.0,42.0
3,Michalis K. Titsias,AUEB,http://www.aueb.gr/users/mtitsias,B-SbkAwAAAAJ,5255.0,30.0
4,Vasilios A. Siris,AUEB,http://www.aueb.gr/users/vsiris,Vj3O0cEAAAAJ,5967.0,31.0
...,...,...,...,...,...,...
20644,Ali C. Begen,Özyeğin University,https://ali.begen.net,ZIZWsXoAAAAJ,5964.0,34.0
20645,Erhan Öztop,Özyeğin University,https://robotics.ozyegin.edu.tr/members/erhan-...,A8YEQMMAAAAJ,3702.0,28.0
20646,Yasar Safkan,Özyeğin University,https://cs.ozyegin.edu.tr/en/faculty/yasarsafkan,NOSCHOLARPAGE,NaN,NaN
20647,Hasan Sözer,Özyeğin University,https://faculty.ozyegin.edu.tr/hsozer,L3FuUX0AAAAJ,847.0,16.0
20648,Emre Sefer,Özyeğin University,http://www.emresefer.com,W5qWthcAAAAJ,253.0,10.0

In [ ]:
new_data.to_csv('cleaned_prof_data_v5')

In [34]:
index = 0
row =new_data.loc[index]

In [30]:
df = pd.DataFrame({'a':[1,2,3],'b':[5,6,7]})

In [31]:
df

   a  b
0  1  5
1  2  6
2  3  7

In [32]:
df.loc[1] = [8,9]

In [33]:
df

   a  b
0  1  5
1  8  9
2  3  7

In [35]:
row

name                                                 P. Vassalos
affiliation                                                 AUEB
homepage       http://pubs.dbs.uni-leipzig.de/aa/aff/Greece/A...
scholar_id                                         NOSCHOLARPAGE
citations                                                    NaN
h-index                                                      NaN
Name: 0, dtype: object

In [36]:
row.tolist()

['P. Vassalos',
 'AUEB',
 'http://pubs.dbs.uni-leipzig.de/aa/aff/Greece/Athens/Athens%20University%20of%20Economics%20and%20Business',
 'NOSCHOLARPAGE',
 nan,
 nan]